version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    assignees:
      - maciaszczykm
      - floreks
      - kgroschoff
    labels:
      - dependencies
      - release-note-none
      - approved
      - ok-to-test

