FROM golang:1.12.9

LABEL maintainer="sebastian.florek@loodse.com"

RUN curl -sL https://deb.nodesource.com/setup_11.x | bash -
RUN apt-get update && apt-get install -y \
    make \
    nodejs

CMD [""]
