workspace:
  base: /go
  path: src/github.com/kubermatic/dashboard-v2

pipeline:
  cache-restore:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  dependencies:
    image: node:8
    commands:
      - make install

  static-check:
    image: node:8
    commands:
      - make check

  node-dist:
    image: node:8
    commands:
      - make dist

  test:
    image: kubermatic/chrome-headless:v0.2
    commands:
      - make test-headless

  e2e:
    image: atlassianlabs/docker-node-jdk-chrome-firefox:2018-12-10
    secrets: [kubermatic_e2e_username, kubermatic_e2e_password]
    commands:
      - npm run e2e

  build:
    image: golang:1.10
    commands:
      - CGO_ENABLED=0 make build

  docker-always:
    group: push
    image: plugins/docker
    repo: kubermatic/ui-v2
    password: ${DOCKER_PASSWORD}
    username: ${DOCKER_USERNAME}
    tags:
      - ${DRONE_COMMIT}
    secrets: [ docker_username, docker_password ]

  docker-master:
    group: push
    image: plugins/docker
    repo: kubermatic/ui-v2
    password: ${DOCKER_PASSWORD}
    username: ${DOCKER_USERNAME}
    tags:
      - master
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  docker-release:
    group: push
    image: plugins/docker
    repo: kubermatic/ui-v2
    password: ${DOCKER_PASSWORD}
    username: ${DOCKER_USERNAME}
    tags:
      - ${DRONE_TAG}
      - latest
    secrets: [ docker_username, docker_password ]
    when:
      event: [tag]

  deploy-dev:
    group: deploy
    image: kubeciio/kubectl:0.2
    pull: true
    kubectl: set image deployment/kubermatic-ui-v2 webserver=kubermatic/ui-v2:{{ .DroneCommit }}
    namespace: kubermatic
    secrets:
      - source: kubeconfig_dev
        target: kubeconfig
    when:
      branch: master

  deploy-cloud:
    group: deploy
    image: kubeciio/kubectl:0.2
    pull: true
    kubectl: set image deployment/kubermatic-ui-v2 webserver=kubermatic/ui-v2:{{ .DroneCommit }}
    namespace: kubermatic
    secrets:
    - source: kubeconfig_cloud
      target: kubeconfig
    when:
      branch: master

  cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  slack-failure:
    group: notify
    image: kubermaticbot/drone-slack
    pull: true
    webhook: https://hooks.slack.com/services/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
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?v=4&s=200
    recipient: ${DRONE_COMMIT_AUTHOR}
    image_url: https://media.giphy.com/media/m6tmCnGCNvTby/giphy-downsized.gif
    template: >
        Your build failed! Shame. Shame. Shame.
        ${DRONE_BUILD_LINK}
    author_recipient_mapping:
      - alvaroaleman=alvaro
      - cbrgm=christian
      - glower=igor.komlew
      - guusvw=guus
      - j3ank=eugenia
      - kdomanski=kamil
      - kgroschoff=kristin.groschoff
      - kron4eg=artiom
      - mrIncompetent=henrik
      - p0lyn0mial=lukasz
      - pkavajin=patrick
      - scheeles=sebastian
      - thz=tobias.hintze
      - toschneck=tobias.schneck
      - xrstf=christoph
      - xmudrii=marko
      - maciaszczykm=marcin
      - floreks=sebastian.florek
    when:
      status: [ failure ]

  slack-deploy:
    group: notify
    image: kubermaticbot/drone-slack
    pull: true
    webhook: https://hooks.slack.com/services/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
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?v=4&s=200
    channel: dev
    template: >
        ${DRONE_COMMIT_AUTHOR} deployed a new Dashboard to dev & cloud. :heart:
    when:
      status: [ success ]
      branch: master
