workspace:
  base: /go
  path: src/github.com/kubermatic/dashboard-v2

pipeline:
  dependencies:
    image: node:8
    commands:
      - make install

linting:
  image: node:8
  commands:
    - make lint

  node-dist:
    image: node:8
    commands:
      - make dist

  build:
    image: golang:1.8.3
    commands:
      - CGO_ENABLED=0 make build

  docker-always:
    group: push
    image: plugins/docker
    repo: kubermatic/ui-v2
    password: ${DOCKER_PASSWORD}
    username: ${DOCKER_USERNAME}
    tags:
      - ${DRONE_COMMIT}
    secrets: [ docker_username, docker_password ]

  docker-master:
    group: push
    image: plugins/docker
    repo: kubermatic/ui-v2
    password: ${DOCKER_PASSWORD}
    username: ${DOCKER_USERNAME}
    tags:
      - master
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  docker-release:
    group: push
    image: plugins/docker
    repo: kubermatic/ui-v2
    password: ${DOCKER_PASSWORD}
    username: ${DOCKER_USERNAME}
    tags:
      - ${DRONE_TAG}
      - latest
    secrets: [ docker_username, docker_password ]
    when:
      event: [tag]

  deploy-dev:
    group: deploy
    image: gcr.io/google_containers/hyperkube-amd64:v1.6.10
    commands:
      - echo $KUBECONFIG | base64 -d > kubeconfig
      - /hyperkube kubectl --kubeconfig kubeconfig -n kubermatic set image deployment/kubermatic-ui-v2 webserver=kubermatic/ui-v2:$DRONE_COMMIT
    secrets: [ kubeconfig ]
    when:
      branch: master

  slack-failure:
    group: notify
    image: kubermaticbot/drone-slack
    webhook: https://hooks.slack.com/services/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
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?v=4&s=200
    recipient: ${DRONE_COMMIT_AUTHOR}
    image_url: https://media.giphy.com/media/m6tmCnGCNvTby/giphy-downsized.gif
    template: >
        Your build failed! Shame. Shame. Shame.
    author_recipient_mapping:
      - mrIncompetent=henrik
      - metalmatze=matthias
      - andriisoldatenko=a_soldatenko
      - guusvw=guus
      - realfake=luk
      - scheeles=sebastian
      - chaosaffe=jason
      - zsemenyuk=zsemenyuk
      - j3ank=eugenia
    when:
      status: [ failure ]

  slack-deploy:
    group: notify
    image: kubermaticbot/drone-slack
    webhook: https://hooks.slack.com/services/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
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?v=4&s=200
    channel: dev
    image_url: http://thecatapi.com/api/images/get?format=src&type=gif&asdasdasd=${DRONE_COMMIT}
    template: >
        We just deployed a new version of the Dashboard-V2 to dev! :heart:
    when:
      status: [ success ]
      branch: master
