[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v1.1.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "v1.10.0"

[prune]
  go-tests = true
  unused-packages = true
