// Code generated by go-swagger; DO NOT EDIT.

package vmwareclouddirector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListProjectVMwareCloudDirectorPlacementPoliciesParams creates a new ListProjectVMwareCloudDirectorPlacementPoliciesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListProjectVMwareCloudDirectorPlacementPoliciesParams() *ListProjectVMwareCloudDirectorPlacementPoliciesParams {
	return &ListProjectVMwareCloudDirectorPlacementPoliciesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListProjectVMwareCloudDirectorPlacementPoliciesParamsWithTimeout creates a new ListProjectVMwareCloudDirectorPlacementPoliciesParams object
// with the ability to set a timeout on a request.
func NewListProjectVMwareCloudDirectorPlacementPoliciesParamsWithTimeout(timeout time.Duration) *ListProjectVMwareCloudDirectorPlacementPoliciesParams {
	return &ListProjectVMwareCloudDirectorPlacementPoliciesParams{
		timeout: timeout,
	}
}

// NewListProjectVMwareCloudDirectorPlacementPoliciesParamsWithContext creates a new ListProjectVMwareCloudDirectorPlacementPoliciesParams object
// with the ability to set a context for a request.
func NewListProjectVMwareCloudDirectorPlacementPoliciesParamsWithContext(ctx context.Context) *ListProjectVMwareCloudDirectorPlacementPoliciesParams {
	return &ListProjectVMwareCloudDirectorPlacementPoliciesParams{
		Context: ctx,
	}
}

// NewListProjectVMwareCloudDirectorPlacementPoliciesParamsWithHTTPClient creates a new ListProjectVMwareCloudDirectorPlacementPoliciesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListProjectVMwareCloudDirectorPlacementPoliciesParamsWithHTTPClient(client *http.Client) *ListProjectVMwareCloudDirectorPlacementPoliciesParams {
	return &ListProjectVMwareCloudDirectorPlacementPoliciesParams{
		HTTPClient: client,
	}
}

/*
ListProjectVMwareCloudDirectorPlacementPoliciesParams contains all the parameters to send to the API endpoint

	for the list project v mware cloud director placement policies operation.

	Typically these are written to a http.Request.
*/
type ListProjectVMwareCloudDirectorPlacementPoliciesParams struct {

	// APIToken.
	APIToken *string

	// Credential.
	Credential *string

	// Organization.
	Organization *string

	// Password.
	Password *string

	// Username.
	Username *string

	// VDC.
	VDC *string

	/* Dc.

	   KKP Datacenter to use for endpoint
	*/
	DC string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list project v mware cloud director placement policies params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) WithDefaults() *ListProjectVMwareCloudDirectorPlacementPoliciesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list project v mware cloud director placement policies params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) WithTimeout(timeout time.Duration) *ListProjectVMwareCloudDirectorPlacementPoliciesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) WithContext(ctx context.Context) *ListProjectVMwareCloudDirectorPlacementPoliciesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) WithHTTPClient(client *http.Client) *ListProjectVMwareCloudDirectorPlacementPoliciesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIToken adds the aPIToken to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) WithAPIToken(aPIToken *string) *ListProjectVMwareCloudDirectorPlacementPoliciesParams {
	o.SetAPIToken(aPIToken)
	return o
}

// SetAPIToken adds the apiToken to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) SetAPIToken(aPIToken *string) {
	o.APIToken = aPIToken
}

// WithCredential adds the credential to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) WithCredential(credential *string) *ListProjectVMwareCloudDirectorPlacementPoliciesParams {
	o.SetCredential(credential)
	return o
}

// SetCredential adds the credential to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) SetCredential(credential *string) {
	o.Credential = credential
}

// WithOrganization adds the organization to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) WithOrganization(organization *string) *ListProjectVMwareCloudDirectorPlacementPoliciesParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) SetOrganization(organization *string) {
	o.Organization = organization
}

// WithPassword adds the password to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) WithPassword(password *string) *ListProjectVMwareCloudDirectorPlacementPoliciesParams {
	o.SetPassword(password)
	return o
}

// SetPassword adds the password to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) SetPassword(password *string) {
	o.Password = password
}

// WithUsername adds the username to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) WithUsername(username *string) *ListProjectVMwareCloudDirectorPlacementPoliciesParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) SetUsername(username *string) {
	o.Username = username
}

// WithVDC adds the vDC to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) WithVDC(vDC *string) *ListProjectVMwareCloudDirectorPlacementPoliciesParams {
	o.SetVDC(vDC)
	return o
}

// SetVDC adds the vDC to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) SetVDC(vDC *string) {
	o.VDC = vDC
}

// WithDC adds the dc to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) WithDC(dc string) *ListProjectVMwareCloudDirectorPlacementPoliciesParams {
	o.SetDC(dc)
	return o
}

// SetDC adds the dc to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) SetDC(dc string) {
	o.DC = dc
}

// WithProjectID adds the projectID to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) WithProjectID(projectID string) *ListProjectVMwareCloudDirectorPlacementPoliciesParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the list project v mware cloud director placement policies params
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *ListProjectVMwareCloudDirectorPlacementPoliciesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.APIToken != nil {

		// header param APIToken
		if err := r.SetHeaderParam("APIToken", *o.APIToken); err != nil {
			return err
		}
	}

	if o.Credential != nil {

		// header param Credential
		if err := r.SetHeaderParam("Credential", *o.Credential); err != nil {
			return err
		}
	}

	if o.Organization != nil {

		// header param Organization
		if err := r.SetHeaderParam("Organization", *o.Organization); err != nil {
			return err
		}
	}

	if o.Password != nil {

		// header param Password
		if err := r.SetHeaderParam("Password", *o.Password); err != nil {
			return err
		}
	}

	if o.Username != nil {

		// header param Username
		if err := r.SetHeaderParam("Username", *o.Username); err != nil {
			return err
		}
	}

	if o.VDC != nil {

		// header param VDC
		if err := r.SetHeaderParam("VDC", *o.VDC); err != nil {
			return err
		}
	}

	// path param dc
	if err := r.SetPathParam("dc", o.DC); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
