// Code generated by go-swagger; DO NOT EDIT.

package vmwareclouddirector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"k8c.io/dashboard/v2/pkg/test/e2e/utils/apiclient/models"
)

// ListVMwareCloudDirectorPlacementPoliciesNoCredentialsReader is a Reader for the ListVMwareCloudDirectorPlacementPoliciesNoCredentials structure.
type ListVMwareCloudDirectorPlacementPoliciesNoCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListVMwareCloudDirectorPlacementPoliciesNoCredentialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListVMwareCloudDirectorPlacementPoliciesNoCredentialsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListVMwareCloudDirectorPlacementPoliciesNoCredentialsOK creates a ListVMwareCloudDirectorPlacementPoliciesNoCredentialsOK with default headers values
func NewListVMwareCloudDirectorPlacementPoliciesNoCredentialsOK() *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsOK {
	return &ListVMwareCloudDirectorPlacementPoliciesNoCredentialsOK{}
}

/*
ListVMwareCloudDirectorPlacementPoliciesNoCredentialsOK describes a response with status code 200, with default header values.

VMwareCloudDirectorPlacementPolicyList
*/
type ListVMwareCloudDirectorPlacementPoliciesNoCredentialsOK struct {
	Payload models.VMwareCloudDirectorPlacementPolicyList
}

// IsSuccess returns true when this list v mware cloud director placement policies no credentials o k response has a 2xx status code
func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list v mware cloud director placement policies no credentials o k response has a 3xx status code
func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list v mware cloud director placement policies no credentials o k response has a 4xx status code
func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list v mware cloud director placement policies no credentials o k response has a 5xx status code
func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list v mware cloud director placement policies no credentials o k response a status code equal to that given
func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/clusters/{cluster_id}/providers/vmwareclouddirector/placementpolicies][%d] listVMwareCloudDirectorPlacementPoliciesNoCredentialsOK  %+v", 200, o.Payload)
}

func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsOK) String() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/clusters/{cluster_id}/providers/vmwareclouddirector/placementpolicies][%d] listVMwareCloudDirectorPlacementPoliciesNoCredentialsOK  %+v", 200, o.Payload)
}

func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsOK) GetPayload() models.VMwareCloudDirectorPlacementPolicyList {
	return o.Payload
}

func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListVMwareCloudDirectorPlacementPoliciesNoCredentialsDefault creates a ListVMwareCloudDirectorPlacementPoliciesNoCredentialsDefault with default headers values
func NewListVMwareCloudDirectorPlacementPoliciesNoCredentialsDefault(code int) *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsDefault {
	return &ListVMwareCloudDirectorPlacementPoliciesNoCredentialsDefault{
		_statusCode: code,
	}
}

/*
ListVMwareCloudDirectorPlacementPoliciesNoCredentialsDefault describes a response with status code -1, with default header values.

errorResponse
*/
type ListVMwareCloudDirectorPlacementPoliciesNoCredentialsDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the list v mware cloud director placement policies no credentials default response
func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this list v mware cloud director placement policies no credentials default response has a 2xx status code
func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list v mware cloud director placement policies no credentials default response has a 3xx status code
func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list v mware cloud director placement policies no credentials default response has a 4xx status code
func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list v mware cloud director placement policies no credentials default response has a 5xx status code
func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list v mware cloud director placement policies no credentials default response a status code equal to that given
func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/clusters/{cluster_id}/providers/vmwareclouddirector/placementpolicies][%d] listVMwareCloudDirectorPlacementPoliciesNoCredentials default  %+v", o._statusCode, o.Payload)
}

func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsDefault) String() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/clusters/{cluster_id}/providers/vmwareclouddirector/placementpolicies][%d] listVMwareCloudDirectorPlacementPoliciesNoCredentials default  %+v", o._statusCode, o.Payload)
}

func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListVMwareCloudDirectorPlacementPoliciesNoCredentialsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
