// Code generated by go-swagger; DO NOT EDIT.

package gke

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"k8c.io/dashboard/v2/pkg/test/e2e/utils/apiclient/models"
)

// ListProjectGCPVMSizesReader is a Reader for the ListProjectGCPVMSizes structure.
type ListProjectGCPVMSizesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListProjectGCPVMSizesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListProjectGCPVMSizesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListProjectGCPVMSizesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListProjectGCPVMSizesOK creates a ListProjectGCPVMSizesOK with default headers values
func NewListProjectGCPVMSizesOK() *ListProjectGCPVMSizesOK {
	return &ListProjectGCPVMSizesOK{}
}

/*
ListProjectGCPVMSizesOK describes a response with status code 200, with default header values.

GCPMachineSizeList
*/
type ListProjectGCPVMSizesOK struct {
	Payload models.GCPMachineSizeList
}

// IsSuccess returns true when this list project g c p Vm sizes o k response has a 2xx status code
func (o *ListProjectGCPVMSizesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list project g c p Vm sizes o k response has a 3xx status code
func (o *ListProjectGCPVMSizesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list project g c p Vm sizes o k response has a 4xx status code
func (o *ListProjectGCPVMSizesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list project g c p Vm sizes o k response has a 5xx status code
func (o *ListProjectGCPVMSizesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list project g c p Vm sizes o k response a status code equal to that given
func (o *ListProjectGCPVMSizesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list project g c p Vm sizes o k response
func (o *ListProjectGCPVMSizesOK) Code() int {
	return 200
}

func (o *ListProjectGCPVMSizesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/providers/gcp/vmsizes][%d] listProjectGCPVmSizesOK %s", 200, payload)
}

func (o *ListProjectGCPVMSizesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/providers/gcp/vmsizes][%d] listProjectGCPVmSizesOK %s", 200, payload)
}

func (o *ListProjectGCPVMSizesOK) GetPayload() models.GCPMachineSizeList {
	return o.Payload
}

func (o *ListProjectGCPVMSizesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListProjectGCPVMSizesDefault creates a ListProjectGCPVMSizesDefault with default headers values
func NewListProjectGCPVMSizesDefault(code int) *ListProjectGCPVMSizesDefault {
	return &ListProjectGCPVMSizesDefault{
		_statusCode: code,
	}
}

/*
ListProjectGCPVMSizesDefault describes a response with status code -1, with default header values.

errorResponse
*/
type ListProjectGCPVMSizesDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// IsSuccess returns true when this list project g c p VM sizes default response has a 2xx status code
func (o *ListProjectGCPVMSizesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list project g c p VM sizes default response has a 3xx status code
func (o *ListProjectGCPVMSizesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list project g c p VM sizes default response has a 4xx status code
func (o *ListProjectGCPVMSizesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list project g c p VM sizes default response has a 5xx status code
func (o *ListProjectGCPVMSizesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list project g c p VM sizes default response a status code equal to that given
func (o *ListProjectGCPVMSizesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list project g c p VM sizes default response
func (o *ListProjectGCPVMSizesDefault) Code() int {
	return o._statusCode
}

func (o *ListProjectGCPVMSizesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/providers/gcp/vmsizes][%d] listProjectGCPVMSizes default %s", o._statusCode, payload)
}

func (o *ListProjectGCPVMSizesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/providers/gcp/vmsizes][%d] listProjectGCPVMSizes default %s", o._statusCode, payload)
}

func (o *ListProjectGCPVMSizesDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListProjectGCPVMSizesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
