#!/bin/sh
# Copyright 2022 The Kubermatic Kubernetes Platform contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. "$(dirname "$0")/_/husky.sh"
cd modules/web/.husky

# If there are no changes in modules/web, exit the hook early so we don't run on BE-only changes.
# Since we cd into husky dir, run git diff based on git root directory
web_dir_path="$(git rev-parse --show-toplevel)/modules/web"

if git diff --quiet -- $web_dir_path || git diff --quiet --cached -- $web_dir_path
then
  npx lint-staged
  npm run check
else
  exit 0
fi
