// Code generated by go-swagger; DO NOT EDIT.

package admin

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"k8c.io/dashboard/v2/pkg/test/e2e/utils/apiclient/models"
)

// NewPatchpolicyTemplateParams creates a new PatchpolicyTemplateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchpolicyTemplateParams() *PatchpolicyTemplateParams {
	return &PatchpolicyTemplateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchpolicyTemplateParamsWithTimeout creates a new PatchpolicyTemplateParams object
// with the ability to set a timeout on a request.
func NewPatchpolicyTemplateParamsWithTimeout(timeout time.Duration) *PatchpolicyTemplateParams {
	return &PatchpolicyTemplateParams{
		timeout: timeout,
	}
}

// NewPatchpolicyTemplateParamsWithContext creates a new PatchpolicyTemplateParams object
// with the ability to set a context for a request.
func NewPatchpolicyTemplateParamsWithContext(ctx context.Context) *PatchpolicyTemplateParams {
	return &PatchpolicyTemplateParams{
		Context: ctx,
	}
}

// NewPatchpolicyTemplateParamsWithHTTPClient creates a new PatchpolicyTemplateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchpolicyTemplateParamsWithHTTPClient(client *http.Client) *PatchpolicyTemplateParams {
	return &PatchpolicyTemplateParams{
		HTTPClient: client,
	}
}

/*
PatchpolicyTemplateParams contains all the parameters to send to the API endpoint

	for the patchpolicy template operation.

	Typically these are written to a http.Request.
*/
type PatchpolicyTemplateParams struct {

	// Spec.
	Spec *models.PolicyTemplateSpec

	// TemplateName.
	PolicyTemplateName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patchpolicy template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchpolicyTemplateParams) WithDefaults() *PatchpolicyTemplateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patchpolicy template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchpolicyTemplateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patchpolicy template params
func (o *PatchpolicyTemplateParams) WithTimeout(timeout time.Duration) *PatchpolicyTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patchpolicy template params
func (o *PatchpolicyTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patchpolicy template params
func (o *PatchpolicyTemplateParams) WithContext(ctx context.Context) *PatchpolicyTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patchpolicy template params
func (o *PatchpolicyTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patchpolicy template params
func (o *PatchpolicyTemplateParams) WithHTTPClient(client *http.Client) *PatchpolicyTemplateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patchpolicy template params
func (o *PatchpolicyTemplateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSpec adds the spec to the patchpolicy template params
func (o *PatchpolicyTemplateParams) WithSpec(spec *models.PolicyTemplateSpec) *PatchpolicyTemplateParams {
	o.SetSpec(spec)
	return o
}

// SetSpec adds the spec to the patchpolicy template params
func (o *PatchpolicyTemplateParams) SetSpec(spec *models.PolicyTemplateSpec) {
	o.Spec = spec
}

// WithPolicyTemplateName adds the templateName to the patchpolicy template params
func (o *PatchpolicyTemplateParams) WithPolicyTemplateName(templateName string) *PatchpolicyTemplateParams {
	o.SetPolicyTemplateName(templateName)
	return o
}

// SetPolicyTemplateName adds the templateName to the patchpolicy template params
func (o *PatchpolicyTemplateParams) SetPolicyTemplateName(templateName string) {
	o.PolicyTemplateName = templateName
}

// WriteToRequest writes these params to a swagger request
func (o *PatchpolicyTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Spec != nil {
		if err := r.SetBodyParam(o.Spec); err != nil {
			return err
		}
	}

	// path param template_name
	if err := r.SetPathParam("template_name", o.PolicyTemplateName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
