// Code generated by go-swagger; DO NOT EDIT.

package aks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListProjectAKSLocationsParams creates a new ListProjectAKSLocationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListProjectAKSLocationsParams() *ListProjectAKSLocationsParams {
	return &ListProjectAKSLocationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListProjectAKSLocationsParamsWithTimeout creates a new ListProjectAKSLocationsParams object
// with the ability to set a timeout on a request.
func NewListProjectAKSLocationsParamsWithTimeout(timeout time.Duration) *ListProjectAKSLocationsParams {
	return &ListProjectAKSLocationsParams{
		timeout: timeout,
	}
}

// NewListProjectAKSLocationsParamsWithContext creates a new ListProjectAKSLocationsParams object
// with the ability to set a context for a request.
func NewListProjectAKSLocationsParamsWithContext(ctx context.Context) *ListProjectAKSLocationsParams {
	return &ListProjectAKSLocationsParams{
		Context: ctx,
	}
}

// NewListProjectAKSLocationsParamsWithHTTPClient creates a new ListProjectAKSLocationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListProjectAKSLocationsParamsWithHTTPClient(client *http.Client) *ListProjectAKSLocationsParams {
	return &ListProjectAKSLocationsParams{
		HTTPClient: client,
	}
}

/*
ListProjectAKSLocationsParams contains all the parameters to send to the API endpoint

	for the list project a k s locations operation.

	Typically these are written to a http.Request.
*/
type ListProjectAKSLocationsParams struct {

	// ClientID.
	ClientID *string

	// ClientSecret.
	ClientSecret *string

	// Credential.
	Credential *string

	// SubscriptionID.
	SubscriptionID *string

	// TenantID.
	TenantID *string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list project a k s locations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListProjectAKSLocationsParams) WithDefaults() *ListProjectAKSLocationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list project a k s locations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListProjectAKSLocationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list project a k s locations params
func (o *ListProjectAKSLocationsParams) WithTimeout(timeout time.Duration) *ListProjectAKSLocationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list project a k s locations params
func (o *ListProjectAKSLocationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list project a k s locations params
func (o *ListProjectAKSLocationsParams) WithContext(ctx context.Context) *ListProjectAKSLocationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list project a k s locations params
func (o *ListProjectAKSLocationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list project a k s locations params
func (o *ListProjectAKSLocationsParams) WithHTTPClient(client *http.Client) *ListProjectAKSLocationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list project a k s locations params
func (o *ListProjectAKSLocationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClientID adds the clientID to the list project a k s locations params
func (o *ListProjectAKSLocationsParams) WithClientID(clientID *string) *ListProjectAKSLocationsParams {
	o.SetClientID(clientID)
	return o
}

// SetClientID adds the clientId to the list project a k s locations params
func (o *ListProjectAKSLocationsParams) SetClientID(clientID *string) {
	o.ClientID = clientID
}

// WithClientSecret adds the clientSecret to the list project a k s locations params
func (o *ListProjectAKSLocationsParams) WithClientSecret(clientSecret *string) *ListProjectAKSLocationsParams {
	o.SetClientSecret(clientSecret)
	return o
}

// SetClientSecret adds the clientSecret to the list project a k s locations params
func (o *ListProjectAKSLocationsParams) SetClientSecret(clientSecret *string) {
	o.ClientSecret = clientSecret
}

// WithCredential adds the credential to the list project a k s locations params
func (o *ListProjectAKSLocationsParams) WithCredential(credential *string) *ListProjectAKSLocationsParams {
	o.SetCredential(credential)
	return o
}

// SetCredential adds the credential to the list project a k s locations params
func (o *ListProjectAKSLocationsParams) SetCredential(credential *string) {
	o.Credential = credential
}

// WithSubscriptionID adds the subscriptionID to the list project a k s locations params
func (o *ListProjectAKSLocationsParams) WithSubscriptionID(subscriptionID *string) *ListProjectAKSLocationsParams {
	o.SetSubscriptionID(subscriptionID)
	return o
}

// SetSubscriptionID adds the subscriptionId to the list project a k s locations params
func (o *ListProjectAKSLocationsParams) SetSubscriptionID(subscriptionID *string) {
	o.SubscriptionID = subscriptionID
}

// WithTenantID adds the tenantID to the list project a k s locations params
func (o *ListProjectAKSLocationsParams) WithTenantID(tenantID *string) *ListProjectAKSLocationsParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the list project a k s locations params
func (o *ListProjectAKSLocationsParams) SetTenantID(tenantID *string) {
	o.TenantID = tenantID
}

// WithProjectID adds the projectID to the list project a k s locations params
func (o *ListProjectAKSLocationsParams) WithProjectID(projectID string) *ListProjectAKSLocationsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the list project a k s locations params
func (o *ListProjectAKSLocationsParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *ListProjectAKSLocationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ClientID != nil {

		// header param ClientID
		if err := r.SetHeaderParam("ClientID", *o.ClientID); err != nil {
			return err
		}
	}

	if o.ClientSecret != nil {

		// header param ClientSecret
		if err := r.SetHeaderParam("ClientSecret", *o.ClientSecret); err != nil {
			return err
		}
	}

	if o.Credential != nil {

		// header param Credential
		if err := r.SetHeaderParam("Credential", *o.Credential); err != nil {
			return err
		}
	}

	if o.SubscriptionID != nil {

		// header param SubscriptionID
		if err := r.SetHeaderParam("SubscriptionID", *o.SubscriptionID); err != nil {
			return err
		}
	}

	if o.TenantID != nil {

		// header param TenantID
		if err := r.SetHeaderParam("TenantID", *o.TenantID); err != nil {
			return err
		}
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
