// Code generated by go-swagger; DO NOT EDIT.

package aks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"k8c.io/dashboard/v2/pkg/test/e2e/utils/apiclient/models"
)

// ValidateProjectAKSCredentialsReader is a Reader for the ValidateProjectAKSCredentials structure.
type ValidateProjectAKSCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ValidateProjectAKSCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewValidateProjectAKSCredentialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewValidateProjectAKSCredentialsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewValidateProjectAKSCredentialsOK creates a ValidateProjectAKSCredentialsOK with default headers values
func NewValidateProjectAKSCredentialsOK() *ValidateProjectAKSCredentialsOK {
	return &ValidateProjectAKSCredentialsOK{}
}

/*
ValidateProjectAKSCredentialsOK describes a response with status code 200, with default header values.

EmptyResponse is a empty response
*/
type ValidateProjectAKSCredentialsOK struct {
}

// IsSuccess returns true when this validate project a k s credentials o k response has a 2xx status code
func (o *ValidateProjectAKSCredentialsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this validate project a k s credentials o k response has a 3xx status code
func (o *ValidateProjectAKSCredentialsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this validate project a k s credentials o k response has a 4xx status code
func (o *ValidateProjectAKSCredentialsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this validate project a k s credentials o k response has a 5xx status code
func (o *ValidateProjectAKSCredentialsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this validate project a k s credentials o k response a status code equal to that given
func (o *ValidateProjectAKSCredentialsOK) IsCode(code int) bool {
	return code == 200
}

func (o *ValidateProjectAKSCredentialsOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/providers/aks/validatecredentials][%d] validateProjectAKSCredentialsOK ", 200)
}

func (o *ValidateProjectAKSCredentialsOK) String() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/providers/aks/validatecredentials][%d] validateProjectAKSCredentialsOK ", 200)
}

func (o *ValidateProjectAKSCredentialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewValidateProjectAKSCredentialsDefault creates a ValidateProjectAKSCredentialsDefault with default headers values
func NewValidateProjectAKSCredentialsDefault(code int) *ValidateProjectAKSCredentialsDefault {
	return &ValidateProjectAKSCredentialsDefault{
		_statusCode: code,
	}
}

/*
ValidateProjectAKSCredentialsDefault describes a response with status code -1, with default header values.

errorResponse
*/
type ValidateProjectAKSCredentialsDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the validate project a k s credentials default response
func (o *ValidateProjectAKSCredentialsDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this validate project a k s credentials default response has a 2xx status code
func (o *ValidateProjectAKSCredentialsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this validate project a k s credentials default response has a 3xx status code
func (o *ValidateProjectAKSCredentialsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this validate project a k s credentials default response has a 4xx status code
func (o *ValidateProjectAKSCredentialsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this validate project a k s credentials default response has a 5xx status code
func (o *ValidateProjectAKSCredentialsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this validate project a k s credentials default response a status code equal to that given
func (o *ValidateProjectAKSCredentialsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ValidateProjectAKSCredentialsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/providers/aks/validatecredentials][%d] validateProjectAKSCredentials default  %+v", o._statusCode, o.Payload)
}

func (o *ValidateProjectAKSCredentialsDefault) String() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/providers/aks/validatecredentials][%d] validateProjectAKSCredentials default  %+v", o._statusCode, o.Payload)
}

func (o *ValidateProjectAKSCredentialsDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ValidateProjectAKSCredentialsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
