// Code generated by go-swagger; DO NOT EDIT.

package openstack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"k8c.io/dashboard/v2/pkg/test/e2e/utils/apiclient/models"
)

// ListOpenstackServerGroupsNoCredentialsReader is a Reader for the ListOpenstackServerGroupsNoCredentials structure.
type ListOpenstackServerGroupsNoCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListOpenstackServerGroupsNoCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListOpenstackServerGroupsNoCredentialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListOpenstackServerGroupsNoCredentialsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListOpenstackServerGroupsNoCredentialsOK creates a ListOpenstackServerGroupsNoCredentialsOK with default headers values
func NewListOpenstackServerGroupsNoCredentialsOK() *ListOpenstackServerGroupsNoCredentialsOK {
	return &ListOpenstackServerGroupsNoCredentialsOK{}
}

/*
ListOpenstackServerGroupsNoCredentialsOK describes a response with status code 200, with default header values.

OpenstackServerGroup
*/
type ListOpenstackServerGroupsNoCredentialsOK struct {
	Payload []*models.OpenstackServerGroup
}

// IsSuccess returns true when this list openstack server groups no credentials o k response has a 2xx status code
func (o *ListOpenstackServerGroupsNoCredentialsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list openstack server groups no credentials o k response has a 3xx status code
func (o *ListOpenstackServerGroupsNoCredentialsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list openstack server groups no credentials o k response has a 4xx status code
func (o *ListOpenstackServerGroupsNoCredentialsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list openstack server groups no credentials o k response has a 5xx status code
func (o *ListOpenstackServerGroupsNoCredentialsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list openstack server groups no credentials o k response a status code equal to that given
func (o *ListOpenstackServerGroupsNoCredentialsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list openstack server groups no credentials o k response
func (o *ListOpenstackServerGroupsNoCredentialsOK) Code() int {
	return 200
}

func (o *ListOpenstackServerGroupsNoCredentialsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/clusters/{cluster_id}/providers/openstack/servergroups][%d] listOpenstackServerGroupsNoCredentialsOK %s", 200, payload)
}

func (o *ListOpenstackServerGroupsNoCredentialsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/clusters/{cluster_id}/providers/openstack/servergroups][%d] listOpenstackServerGroupsNoCredentialsOK %s", 200, payload)
}

func (o *ListOpenstackServerGroupsNoCredentialsOK) GetPayload() []*models.OpenstackServerGroup {
	return o.Payload
}

func (o *ListOpenstackServerGroupsNoCredentialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListOpenstackServerGroupsNoCredentialsDefault creates a ListOpenstackServerGroupsNoCredentialsDefault with default headers values
func NewListOpenstackServerGroupsNoCredentialsDefault(code int) *ListOpenstackServerGroupsNoCredentialsDefault {
	return &ListOpenstackServerGroupsNoCredentialsDefault{
		_statusCode: code,
	}
}

/*
ListOpenstackServerGroupsNoCredentialsDefault describes a response with status code -1, with default header values.

errorResponse
*/
type ListOpenstackServerGroupsNoCredentialsDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// IsSuccess returns true when this list openstack server groups no credentials default response has a 2xx status code
func (o *ListOpenstackServerGroupsNoCredentialsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list openstack server groups no credentials default response has a 3xx status code
func (o *ListOpenstackServerGroupsNoCredentialsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list openstack server groups no credentials default response has a 4xx status code
func (o *ListOpenstackServerGroupsNoCredentialsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list openstack server groups no credentials default response has a 5xx status code
func (o *ListOpenstackServerGroupsNoCredentialsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list openstack server groups no credentials default response a status code equal to that given
func (o *ListOpenstackServerGroupsNoCredentialsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list openstack server groups no credentials default response
func (o *ListOpenstackServerGroupsNoCredentialsDefault) Code() int {
	return o._statusCode
}

func (o *ListOpenstackServerGroupsNoCredentialsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/clusters/{cluster_id}/providers/openstack/servergroups][%d] listOpenstackServerGroupsNoCredentials default %s", o._statusCode, payload)
}

func (o *ListOpenstackServerGroupsNoCredentialsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/clusters/{cluster_id}/providers/openstack/servergroups][%d] listOpenstackServerGroupsNoCredentials default %s", o._statusCode, payload)
}

func (o *ListOpenstackServerGroupsNoCredentialsDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListOpenstackServerGroupsNoCredentialsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
