// Code generated by go-swagger; DO NOT EDIT.

package backupstoragelocation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListBackupStorageLocationParams creates a new ListBackupStorageLocationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListBackupStorageLocationParams() *ListBackupStorageLocationParams {
	return &ListBackupStorageLocationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListBackupStorageLocationParamsWithTimeout creates a new ListBackupStorageLocationParams object
// with the ability to set a timeout on a request.
func NewListBackupStorageLocationParamsWithTimeout(timeout time.Duration) *ListBackupStorageLocationParams {
	return &ListBackupStorageLocationParams{
		timeout: timeout,
	}
}

// NewListBackupStorageLocationParamsWithContext creates a new ListBackupStorageLocationParams object
// with the ability to set a context for a request.
func NewListBackupStorageLocationParamsWithContext(ctx context.Context) *ListBackupStorageLocationParams {
	return &ListBackupStorageLocationParams{
		Context: ctx,
	}
}

// NewListBackupStorageLocationParamsWithHTTPClient creates a new ListBackupStorageLocationParams object
// with the ability to set a custom HTTPClient for a request.
func NewListBackupStorageLocationParamsWithHTTPClient(client *http.Client) *ListBackupStorageLocationParams {
	return &ListBackupStorageLocationParams{
		HTTPClient: client,
	}
}

/*
ListBackupStorageLocationParams contains all the parameters to send to the API endpoint

	for the list backup storage location operation.

	Typically these are written to a http.Request.
*/
type ListBackupStorageLocationParams struct {

	// ClusterID.
	ClusterID string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list backup storage location params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListBackupStorageLocationParams) WithDefaults() *ListBackupStorageLocationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list backup storage location params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListBackupStorageLocationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list backup storage location params
func (o *ListBackupStorageLocationParams) WithTimeout(timeout time.Duration) *ListBackupStorageLocationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list backup storage location params
func (o *ListBackupStorageLocationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list backup storage location params
func (o *ListBackupStorageLocationParams) WithContext(ctx context.Context) *ListBackupStorageLocationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list backup storage location params
func (o *ListBackupStorageLocationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list backup storage location params
func (o *ListBackupStorageLocationParams) WithHTTPClient(client *http.Client) *ListBackupStorageLocationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list backup storage location params
func (o *ListBackupStorageLocationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the list backup storage location params
func (o *ListBackupStorageLocationParams) WithClusterID(clusterID string) *ListBackupStorageLocationParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the list backup storage location params
func (o *ListBackupStorageLocationParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithProjectID adds the projectID to the list backup storage location params
func (o *ListBackupStorageLocationParams) WithProjectID(projectID string) *ListBackupStorageLocationParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the list backup storage location params
func (o *ListBackupStorageLocationParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *ListBackupStorageLocationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
