// Code generated by go-swagger; DO NOT EDIT.

package user_cluster_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAdmissionPluginsConfigurationParams creates a new GetAdmissionPluginsConfigurationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAdmissionPluginsConfigurationParams() *GetAdmissionPluginsConfigurationParams {
	return &GetAdmissionPluginsConfigurationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAdmissionPluginsConfigurationParamsWithTimeout creates a new GetAdmissionPluginsConfigurationParams object
// with the ability to set a timeout on a request.
func NewGetAdmissionPluginsConfigurationParamsWithTimeout(timeout time.Duration) *GetAdmissionPluginsConfigurationParams {
	return &GetAdmissionPluginsConfigurationParams{
		timeout: timeout,
	}
}

// NewGetAdmissionPluginsConfigurationParamsWithContext creates a new GetAdmissionPluginsConfigurationParams object
// with the ability to set a context for a request.
func NewGetAdmissionPluginsConfigurationParamsWithContext(ctx context.Context) *GetAdmissionPluginsConfigurationParams {
	return &GetAdmissionPluginsConfigurationParams{
		Context: ctx,
	}
}

// NewGetAdmissionPluginsConfigurationParamsWithHTTPClient creates a new GetAdmissionPluginsConfigurationParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAdmissionPluginsConfigurationParamsWithHTTPClient(client *http.Client) *GetAdmissionPluginsConfigurationParams {
	return &GetAdmissionPluginsConfigurationParams{
		HTTPClient: client,
	}
}

/*
GetAdmissionPluginsConfigurationParams contains all the parameters to send to the API endpoint

	for the get admission plugins configuration operation.

	Typically these are written to a http.Request.
*/
type GetAdmissionPluginsConfigurationParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get admission plugins configuration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAdmissionPluginsConfigurationParams) WithDefaults() *GetAdmissionPluginsConfigurationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get admission plugins configuration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAdmissionPluginsConfigurationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get admission plugins configuration params
func (o *GetAdmissionPluginsConfigurationParams) WithTimeout(timeout time.Duration) *GetAdmissionPluginsConfigurationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get admission plugins configuration params
func (o *GetAdmissionPluginsConfigurationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get admission plugins configuration params
func (o *GetAdmissionPluginsConfigurationParams) WithContext(ctx context.Context) *GetAdmissionPluginsConfigurationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get admission plugins configuration params
func (o *GetAdmissionPluginsConfigurationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get admission plugins configuration params
func (o *GetAdmissionPluginsConfigurationParams) WithHTTPClient(client *http.Client) *GetAdmissionPluginsConfigurationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get admission plugins configuration params
func (o *GetAdmissionPluginsConfigurationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAdmissionPluginsConfigurationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
