GET http://localhost:8000/api/v2/projects/pt59hrj4wt/kubernetes/clusters/hwv8mkbhnb/machinedeployments/default-pool
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImE2MDNmMGQ2MDcwNGYyODIwMmUyNjdjMzI1MjU3MzIyMjA3MjA4MTAifQ.eyJpc3MiOiJodHRwczovL2Rldi5rdWJlcm1hdGljLmlvL2RleCIsInN1YiI6IkNoVXhNVFV3TVRJNU1qQTJNVEF6TkRreE1UQXpOVEFTQm1kdmIyZHNaUSIsImF1ZCI6Imt1YmVybWF0aWMiLCJleHAiOjE2Mzk1NTkwMDMsImlhdCI6MTYzOTQ3MjYwMywibm9uY2UiOiJHbHZzVGV3ZTBLemJ3Tm9IU09pT1g0WmdYNTdqd19ISiIsImF0X2hhc2giOiJnaTZ0QUc0M0psSlhxRnZMcU00S3JnIiwiZW1haWwiOiJzZWJhc3RpYW4uZmxvcmVrQGt1YmVybWF0aWMuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJTZWJhc3RpYW4gRmxvcmVrIn0.QD-VsVYAJSyrAxHzmyUIYvQvkL3Z_XyxVdZPEqJrgRk8pMRYhKXsKqFaHqTjf2e3sDpjeEiBst9csnqECWY_jUDeedKpbT0H3RR8AzIpa2Rk6UhIG-mzKZtddd82EUYVl1xtGW83cyZb78trz8DdfRechlZhsQ0sLBTLslLN6DZPo9RGIYaTctrwK1OnINjmgJQPGgHZn8_GyaehvWp0BLKoiVIkcwDAZ3TkH1nN3wlxcyZLcydfCtO0WxAtv-r2ShIvY2XQPN38ucD8F0MEsxbxK4eDNvgpL1HwUaiteXdKRAqw7nrqcSSOBkTe21sRjc4CWJH1Fh6F2HjBemz3nw
###
