// Code generated by go-swagger; DO NOT EDIT.

package anexia

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"k8c.io/dashboard/v2/pkg/test/e2e/utils/apiclient/models"
)

// ListProjectAnexiaDiskTypesReader is a Reader for the ListProjectAnexiaDiskTypes structure.
type ListProjectAnexiaDiskTypesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListProjectAnexiaDiskTypesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListProjectAnexiaDiskTypesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListProjectAnexiaDiskTypesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListProjectAnexiaDiskTypesOK creates a ListProjectAnexiaDiskTypesOK with default headers values
func NewListProjectAnexiaDiskTypesOK() *ListProjectAnexiaDiskTypesOK {
	return &ListProjectAnexiaDiskTypesOK{}
}

/*
ListProjectAnexiaDiskTypesOK describes a response with status code 200, with default header values.

AnexiaDiskTypeList
*/
type ListProjectAnexiaDiskTypesOK struct {
	Payload models.AnexiaDiskTypeList
}

// IsSuccess returns true when this list project anexia disk types o k response has a 2xx status code
func (o *ListProjectAnexiaDiskTypesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list project anexia disk types o k response has a 3xx status code
func (o *ListProjectAnexiaDiskTypesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list project anexia disk types o k response has a 4xx status code
func (o *ListProjectAnexiaDiskTypesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list project anexia disk types o k response has a 5xx status code
func (o *ListProjectAnexiaDiskTypesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list project anexia disk types o k response a status code equal to that given
func (o *ListProjectAnexiaDiskTypesOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListProjectAnexiaDiskTypesOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/providers/anexia/disk-types][%d] listProjectAnexiaDiskTypesOK  %+v", 200, o.Payload)
}

func (o *ListProjectAnexiaDiskTypesOK) String() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/providers/anexia/disk-types][%d] listProjectAnexiaDiskTypesOK  %+v", 200, o.Payload)
}

func (o *ListProjectAnexiaDiskTypesOK) GetPayload() models.AnexiaDiskTypeList {
	return o.Payload
}

func (o *ListProjectAnexiaDiskTypesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListProjectAnexiaDiskTypesDefault creates a ListProjectAnexiaDiskTypesDefault with default headers values
func NewListProjectAnexiaDiskTypesDefault(code int) *ListProjectAnexiaDiskTypesDefault {
	return &ListProjectAnexiaDiskTypesDefault{
		_statusCode: code,
	}
}

/*
ListProjectAnexiaDiskTypesDefault describes a response with status code -1, with default header values.

errorResponse
*/
type ListProjectAnexiaDiskTypesDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the list project anexia disk types default response
func (o *ListProjectAnexiaDiskTypesDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this list project anexia disk types default response has a 2xx status code
func (o *ListProjectAnexiaDiskTypesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list project anexia disk types default response has a 3xx status code
func (o *ListProjectAnexiaDiskTypesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list project anexia disk types default response has a 4xx status code
func (o *ListProjectAnexiaDiskTypesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list project anexia disk types default response has a 5xx status code
func (o *ListProjectAnexiaDiskTypesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list project anexia disk types default response a status code equal to that given
func (o *ListProjectAnexiaDiskTypesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ListProjectAnexiaDiskTypesDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/providers/anexia/disk-types][%d] listProjectAnexiaDiskTypes default  %+v", o._statusCode, o.Payload)
}

func (o *ListProjectAnexiaDiskTypesDefault) String() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/providers/anexia/disk-types][%d] listProjectAnexiaDiskTypes default  %+v", o._statusCode, o.Payload)
}

func (o *ListProjectAnexiaDiskTypesDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListProjectAnexiaDiskTypesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
