// Code generated by go-swagger; DO NOT EDIT.

package anexia

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListProjectAnexiaTemplatesParams creates a new ListProjectAnexiaTemplatesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListProjectAnexiaTemplatesParams() *ListProjectAnexiaTemplatesParams {
	return &ListProjectAnexiaTemplatesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListProjectAnexiaTemplatesParamsWithTimeout creates a new ListProjectAnexiaTemplatesParams object
// with the ability to set a timeout on a request.
func NewListProjectAnexiaTemplatesParamsWithTimeout(timeout time.Duration) *ListProjectAnexiaTemplatesParams {
	return &ListProjectAnexiaTemplatesParams{
		timeout: timeout,
	}
}

// NewListProjectAnexiaTemplatesParamsWithContext creates a new ListProjectAnexiaTemplatesParams object
// with the ability to set a context for a request.
func NewListProjectAnexiaTemplatesParamsWithContext(ctx context.Context) *ListProjectAnexiaTemplatesParams {
	return &ListProjectAnexiaTemplatesParams{
		Context: ctx,
	}
}

// NewListProjectAnexiaTemplatesParamsWithHTTPClient creates a new ListProjectAnexiaTemplatesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListProjectAnexiaTemplatesParamsWithHTTPClient(client *http.Client) *ListProjectAnexiaTemplatesParams {
	return &ListProjectAnexiaTemplatesParams{
		HTTPClient: client,
	}
}

/*
ListProjectAnexiaTemplatesParams contains all the parameters to send to the API endpoint

	for the list project anexia templates operation.

	Typically these are written to a http.Request.
*/
type ListProjectAnexiaTemplatesParams struct {

	// Credential.
	Credential *string

	// Location.
	Location *string

	// Token.
	Token *string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list project anexia templates params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListProjectAnexiaTemplatesParams) WithDefaults() *ListProjectAnexiaTemplatesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list project anexia templates params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListProjectAnexiaTemplatesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list project anexia templates params
func (o *ListProjectAnexiaTemplatesParams) WithTimeout(timeout time.Duration) *ListProjectAnexiaTemplatesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list project anexia templates params
func (o *ListProjectAnexiaTemplatesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list project anexia templates params
func (o *ListProjectAnexiaTemplatesParams) WithContext(ctx context.Context) *ListProjectAnexiaTemplatesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list project anexia templates params
func (o *ListProjectAnexiaTemplatesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list project anexia templates params
func (o *ListProjectAnexiaTemplatesParams) WithHTTPClient(client *http.Client) *ListProjectAnexiaTemplatesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list project anexia templates params
func (o *ListProjectAnexiaTemplatesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCredential adds the credential to the list project anexia templates params
func (o *ListProjectAnexiaTemplatesParams) WithCredential(credential *string) *ListProjectAnexiaTemplatesParams {
	o.SetCredential(credential)
	return o
}

// SetCredential adds the credential to the list project anexia templates params
func (o *ListProjectAnexiaTemplatesParams) SetCredential(credential *string) {
	o.Credential = credential
}

// WithLocation adds the location to the list project anexia templates params
func (o *ListProjectAnexiaTemplatesParams) WithLocation(location *string) *ListProjectAnexiaTemplatesParams {
	o.SetLocation(location)
	return o
}

// SetLocation adds the location to the list project anexia templates params
func (o *ListProjectAnexiaTemplatesParams) SetLocation(location *string) {
	o.Location = location
}

// WithToken adds the token to the list project anexia templates params
func (o *ListProjectAnexiaTemplatesParams) WithToken(token *string) *ListProjectAnexiaTemplatesParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the list project anexia templates params
func (o *ListProjectAnexiaTemplatesParams) SetToken(token *string) {
	o.Token = token
}

// WithProjectID adds the projectID to the list project anexia templates params
func (o *ListProjectAnexiaTemplatesParams) WithProjectID(projectID string) *ListProjectAnexiaTemplatesParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the list project anexia templates params
func (o *ListProjectAnexiaTemplatesParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *ListProjectAnexiaTemplatesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Credential != nil {

		// header param Credential
		if err := r.SetHeaderParam("Credential", *o.Credential); err != nil {
			return err
		}
	}

	if o.Location != nil {

		// header param Location
		if err := r.SetHeaderParam("Location", *o.Location); err != nil {
			return err
		}
	}

	if o.Token != nil {

		// header param Token
		if err := r.SetHeaderParam("Token", *o.Token); err != nil {
			return err
		}
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
