// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AzureSecurityProfile AzureSecurityProfile specifies security settings like TrustedLaunch for an Azure VM.
//
// swagger:model AzureSecurityProfile
type AzureSecurityProfile struct {

	// SecureBootEnabled specifies whether secure boot should be enabled. Only valid when SecurityType is TrustedLaunch.
	SecureBootEnabled bool `json:"secureBootEnabled,omitempty"`

	// SecurityType is the security type of the VM. Supported values (case-sensitive): TrustedLaunch, Standard.
	SecurityType string `json:"securityType,omitempty"`

	// VTpmEnabled specifies whether vTPM should be enabled. Only valid when SecurityType is TrustedLaunch.
	VTpmEnabled bool `json:"vTpmEnabled,omitempty"`
}

// Validate validates this azure security profile
func (m *AzureSecurityProfile) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this azure security profile based on context it is used
func (m *AzureSecurityProfile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AzureSecurityProfile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AzureSecurityProfile) UnmarshalBinary(b []byte) error {
	var res AzureSecurityProfile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
