// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BackupDownloadURL BackupDownloadUrl is the object representing a Backup Download URL.
//
// swagger:model BackupDownloadUrl
type BackupDownloadURL struct {

	// download URL
	DownloadURL string `json:"downloadURL,omitempty"`
}

// Validate validates this backup download Url
func (m *BackupDownloadURL) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this backup download Url based on context it is used
func (m *BackupDownloadURL) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BackupDownloadURL) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BackupDownloadURL) UnmarshalBinary(b []byte) error {
	var res BackupDownloadURL
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
