// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CloneFrom CloneFrom provides the location of the source resource used to generate target resources.
//
// The resource kind is derived from the match criteria.
//
// swagger:model CloneFrom
type CloneFrom struct {

	// Name specifies name of the resource.
	Name string `json:"name,omitempty"`

	// Namespace specifies source resource namespace.
	// +optional
	Namespace string `json:"namespace,omitempty"`
}

// Validate validates this clone from
func (m *CloneFrom) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this clone from based on context it is used
func (m *CloneFrom) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CloneFrom) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CloneFrom) UnmarshalBinary(b []byte) error {
	var res CloneFrom
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
