// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ClusterProxySettings ClusterProxySettings holds the per-cluster HTTP(S) proxy configuration. Empty values mean the
// cluster inherits the datacenter/seed proxy settings.
//
// swagger:model ClusterProxySettings
type ClusterProxySettings struct {

	// HTTPProxy is the proxy server endpoint used for both HTTP and HTTPS egress from the nodes,
	// e.g. "http://proxy.corp.example.com:3128".
	HTTPProxy string `json:"httpProxy,omitempty"`

	// NoProxy is a comma-separated list of domains, IPs or CIDRs for which no proxy should be used.
	NoProxy string `json:"noProxy,omitempty"`
}

// Validate validates this cluster proxy settings
func (m *ClusterProxySettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cluster proxy settings based on context it is used
func (m *ClusterProxySettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClusterProxySettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterProxySettings) UnmarshalBinary(b []byte) error {
	var res ClusterProxySettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
