// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Code code
//
// swagger:model Code
type Code struct {

	// engine
	// Example: \"Rego\". Required.
	Engine string `json:"engine,omitempty"`

	// source
	Source Anything `json:"source,omitempty"`
}

// Validate validates this code
func (m *Code) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this code based on context it is used
func (m *Code) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Code) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Code) UnmarshalBinary(b []byte) error {
	var res Code
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
