// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ConditionStatus condition status
//
// swagger:model ConditionStatus
type ConditionStatus string

// Validate validates this condition status
func (m ConditionStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this condition status based on context it is used
func (m ConditionStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
