// Code generated by go-swagger; DO NOT EDIT.

package models

// DatacenterSpecBringYourOwn DatacenterSpecBringYourOwn describes a datacenter our of bring your own nodes.
//
// swagger:model DatacenterSpecBringYourOwn
type DatacenterSpecBringYourOwn any
