// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Deny Deny specifies a list of conditions used to pass or fail a validation rule.
//
// swagger:model Deny
type Deny struct {

	// conditions
	Conditions ConditionsWrapper `json:"conditions,omitempty"`
}

// Validate validates this deny
func (m *Deny) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this deny based on context it is used
func (m *Deny) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Deny) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Deny) UnmarshalBinary(b []byte) error {
	var res Deny
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
