// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ExternalClusterSpec ExternalClusterSpec defines the external cluster specification.
//
// swagger:model ExternalClusterSpec
type ExternalClusterSpec struct {

	// container runtime
	ContainerRuntime string `json:"containerRuntime,omitempty"`

	// aks cluster spec
	AksClusterSpec *AKSClusterSpec `json:"aksClusterSpec,omitempty"`

	// eks cluster spec
	EksClusterSpec *EKSClusterSpec `json:"eksClusterSpec,omitempty"`

	// gke cluster spec
	GkeClusterSpec *GKEClusterSpec `json:"gkeClusterSpec,omitempty"`

	// kube one cluster spec
	KubeOneClusterSpec *KubeOneClusterSpec `json:"kubeOneClusterSpec,omitempty"`

	// version
	Version Semver `json:"version,omitempty"`
}

// Validate validates this external cluster spec
func (m *ExternalClusterSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAksClusterSpec(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEksClusterSpec(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGkeClusterSpec(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKubeOneClusterSpec(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExternalClusterSpec) validateAksClusterSpec(formats strfmt.Registry) error {
	if swag.IsZero(m.AksClusterSpec) { // not required
		return nil
	}

	if m.AksClusterSpec != nil {
		if err := m.AksClusterSpec.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("aksClusterSpec")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("aksClusterSpec")
			}
			return err
		}
	}

	return nil
}

func (m *ExternalClusterSpec) validateEksClusterSpec(formats strfmt.Registry) error {
	if swag.IsZero(m.EksClusterSpec) { // not required
		return nil
	}

	if m.EksClusterSpec != nil {
		if err := m.EksClusterSpec.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("eksClusterSpec")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("eksClusterSpec")
			}
			return err
		}
	}

	return nil
}

func (m *ExternalClusterSpec) validateGkeClusterSpec(formats strfmt.Registry) error {
	if swag.IsZero(m.GkeClusterSpec) { // not required
		return nil
	}

	if m.GkeClusterSpec != nil {
		if err := m.GkeClusterSpec.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("gkeClusterSpec")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("gkeClusterSpec")
			}
			return err
		}
	}

	return nil
}

func (m *ExternalClusterSpec) validateKubeOneClusterSpec(formats strfmt.Registry) error {
	if swag.IsZero(m.KubeOneClusterSpec) { // not required
		return nil
	}

	if m.KubeOneClusterSpec != nil {
		if err := m.KubeOneClusterSpec.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("kubeOneClusterSpec")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("kubeOneClusterSpec")
			}
			return err
		}
	}

	return nil
}

func (m *ExternalClusterSpec) validateVersion(formats strfmt.Registry) error {
	if swag.IsZero(m.Version) { // not required
		return nil
	}

	if err := m.Version.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("version")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("version")
		}
		return err
	}

	return nil
}

// ContextValidate validate this external cluster spec based on the context it is used
func (m *ExternalClusterSpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAksClusterSpec(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateEksClusterSpec(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateGkeClusterSpec(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateKubeOneClusterSpec(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVersion(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExternalClusterSpec) contextValidateAksClusterSpec(ctx context.Context, formats strfmt.Registry) error {

	if m.AksClusterSpec != nil {
		if err := m.AksClusterSpec.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("aksClusterSpec")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("aksClusterSpec")
			}
			return err
		}
	}

	return nil
}

func (m *ExternalClusterSpec) contextValidateEksClusterSpec(ctx context.Context, formats strfmt.Registry) error {

	if m.EksClusterSpec != nil {
		if err := m.EksClusterSpec.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("eksClusterSpec")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("eksClusterSpec")
			}
			return err
		}
	}

	return nil
}

func (m *ExternalClusterSpec) contextValidateGkeClusterSpec(ctx context.Context, formats strfmt.Registry) error {

	if m.GkeClusterSpec != nil {
		if err := m.GkeClusterSpec.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("gkeClusterSpec")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("gkeClusterSpec")
			}
			return err
		}
	}

	return nil
}

func (m *ExternalClusterSpec) contextValidateKubeOneClusterSpec(ctx context.Context, formats strfmt.Registry) error {

	if m.KubeOneClusterSpec != nil {
		if err := m.KubeOneClusterSpec.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("kubeOneClusterSpec")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("kubeOneClusterSpec")
			}
			return err
		}
	}

	return nil
}

func (m *ExternalClusterSpec) contextValidateVersion(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Version.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("version")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("version")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ExternalClusterSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExternalClusterSpec) UnmarshalBinary(b []byte) error {
	var res ExternalClusterSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
