// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ExternalClusterState external cluster state
//
// swagger:model ExternalClusterState
type ExternalClusterState string

// Validate validates this external cluster state
func (m ExternalClusterState) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this external cluster state based on context it is used
func (m ExternalClusterState) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
