// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FakeCloudSpec FakeCloudSpec specifies access data for a fake cloud.
//
// swagger:model FakeCloudSpec
type FakeCloudSpec struct {

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this fake cloud spec
func (m *FakeCloudSpec) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this fake cloud spec based on context it is used
func (m *FakeCloudSpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FakeCloudSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FakeCloudSpec) UnmarshalBinary(b []byte) error {
	var res FakeCloudSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
