// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// GitAuthMethod +kubebuilder:validation:Enum=password;token;ssh-key
//
// swagger:model GitAuthMethod
type GitAuthMethod string

// Validate validates this git auth method
func (m GitAuthMethod) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this git auth method based on context it is used
func (m GitAuthMethod) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
