// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ImageVerificationType ImageVerificationType selects the type of verification algorithm
// +kubebuilder:validation:Enum=Cosign;SigstoreBundle;Notary
// +kubebuilder:default=Cosign
//
// swagger:model ImageVerificationType
type ImageVerificationType string

// Validate validates this image verification type
func (m ImageVerificationType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this image verification type based on context it is used
func (m ImageVerificationType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
