// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InstancetypeMatcher InstancetypeMatcher references a instancetype that is used to fill fields in the VMI template.
//
// swagger:model InstancetypeMatcher
type InstancetypeMatcher struct {

	// Kind specifies which instancetype resource is referenced.
	// Allowed values are: "VirtualMachineInstancetype" and "VirtualMachineClusterInstancetype".
	// If not specified, "VirtualMachineClusterInstancetype" is used by default.
	//
	// +optional
	Kind string `json:"kind,omitempty"`

	// Name is the name of the VirtualMachineInstancetype or VirtualMachineClusterInstancetype
	Name string `json:"name,omitempty"`

	// RevisionName specifies a ControllerRevision containing a specific copy of the
	// VirtualMachineInstancetype or VirtualMachineClusterInstancetype to be used. This is initially
	// captured the first time the instancetype is applied to the VirtualMachineInstance.
	//
	// +optional
	RevisionName string `json:"revisionName,omitempty"`
}

// Validate validates this instancetype matcher
func (m *InstancetypeMatcher) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this instancetype matcher based on context it is used
func (m *InstancetypeMatcher) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InstancetypeMatcher) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InstancetypeMatcher) UnmarshalBinary(b []byte) error {
	var res InstancetypeMatcher
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
