// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// JoiningScript JoiningScript represent an encoded joining script for machines
//
// swagger:model JoiningScript
type JoiningScript string

// Validate validates this joining script
func (m JoiningScript) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this joining script based on context it is used
func (m JoiningScript) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
