// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// JSONSchemaURL JSONSchemaURL represents a schema url.
//
// swagger:model JSONSchemaURL
type JSONSchemaURL string

// Validate validates this JSON schema URL
func (m JSONSchemaURL) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this JSON schema URL based on context it is used
func (m JSONSchemaURL) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
