// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// KubeVirtInfraVolumeSnapshotClass kube virt infra volume snapshot class
//
// swagger:model KubeVirtInfraVolumeSnapshotClass
type KubeVirtInfraVolumeSnapshotClass struct {

	// Optional: DeletionPolicy defines how the VolumeSnapshotClass should be deleted. Defaults to Delete.
	DeletionPolicy string `json:"deletionPolicy,omitempty"`

	// InfraVolumeSnapshotClass of the volume snapshot class to use on the infrastructure cluster.
	InfraVolumeSnapshotClass string `json:"infraVolumeSnapshotClass,omitempty"`

	// Optional: IsDefaultClass. If true, the created VolumeSnapshotClass in the tenant cluster will be annotated with:
	// snapshot.storage.kubernetes.io/is-default-class: true
	// If missing or false, annotation will be:
	// snapshot.storage.kubernetes.io/is-default-class: false
	IsDefaultClass bool `json:"isDefaultClass,omitempty"`
}

// Validate validates this kube virt infra volume snapshot class
func (m *KubeVirtInfraVolumeSnapshotClass) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this kube virt infra volume snapshot class based on context it is used
func (m *KubeVirtInfraVolumeSnapshotClass) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *KubeVirtInfraVolumeSnapshotClass) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KubeVirtInfraVolumeSnapshotClass) UnmarshalBinary(b []byte) error {
	var res KubeVirtInfraVolumeSnapshotClass
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
