// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NamespacedMode namespaced mode
//
// swagger:model NamespacedMode
type NamespacedMode struct {

	// Enabled indicates whether the single namespace mode is enabled or not.
	Enabled bool `json:"enabled,omitempty"`

	// Namespace is the name of the namespace to be used, if not specified the default "kubevirt-workload" will be used.
	// +kubebuilder:default=kubevirt-workload
	Namespace string `json:"name,omitempty"`
}

// Validate validates this namespaced mode
func (m *NamespacedMode) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this namespaced mode based on context it is used
func (m *NamespacedMode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NamespacedMode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NamespacedMode) UnmarshalBinary(b []byte) error {
	var res NamespacedMode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
