// Code generated by go-swagger; DO NOT EDIT.

package models

// PublicAlibabaCloudSpec PublicAlibabaCloudSpec is a public counterpart of apiv1.AlibabaCloudSpec.
//
// swagger:model PublicAlibabaCloudSpec
type PublicAlibabaCloudSpec any
