// Code generated by go-swagger; DO NOT EDIT.

package models

// PublicAnexiaCloudSpec PublicAnexiaCloudSpec is a public counterpart of apiv1.AnexiaCloudSpec.
//
// swagger:model PublicAnexiaCloudSpec
type PublicAnexiaCloudSpec any
