// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StaticLabel StaticLabel is a label that can be used for the clusters.
//
// swagger:model StaticLabel
type StaticLabel struct {

	// default
	Default bool `json:"default,omitempty"`

	// key
	Key string `json:"key,omitempty"`

	// protected
	Protected bool `json:"protected,omitempty"`

	// values
	Values []string `json:"values"`
}

// Validate validates this static label
func (m *StaticLabel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this static label based on context it is used
func (m *StaticLabel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StaticLabel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StaticLabel) UnmarshalBinary(b []byte) error {
	var res StaticLabel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
