// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// TinkerbellImageSourceType TinkerbellImageSourceType represents a Tinkerbell image source type.
//
// swagger:model TinkerbellImageSourceType
type TinkerbellImageSourceType string

// Validate validates this tinkerbell image source type
func (m TinkerbellImageSourceType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tinkerbell image source type based on context it is used
func (m TinkerbellImageSourceType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
