// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// UID UID is a type that holds unique ID values, including UUIDs.  Because we
// don't ONLY use UUIDs, this is an alias to string.  Being a type captures
// intent and helps make sure that UIDs and names do not get conflated.
//
// swagger:model UID
type UID string

// Validate validates this UID
func (m UID) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this UID based on context it is used
func (m UID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
