// Code generated by go-swagger; DO NOT EDIT.

package gcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"k8c.io/dashboard/v2/pkg/test/e2e/utils/apiclient/models"
)

// ListProjectGCPNetworksReader is a Reader for the ListProjectGCPNetworks structure.
type ListProjectGCPNetworksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListProjectGCPNetworksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListProjectGCPNetworksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListProjectGCPNetworksDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListProjectGCPNetworksOK creates a ListProjectGCPNetworksOK with default headers values
func NewListProjectGCPNetworksOK() *ListProjectGCPNetworksOK {
	return &ListProjectGCPNetworksOK{}
}

/*
ListProjectGCPNetworksOK describes a response with status code 200, with default header values.

GCPNetworkList
*/
type ListProjectGCPNetworksOK struct {
	Payload models.GCPNetworkList
}

// IsSuccess returns true when this list project g c p networks o k response has a 2xx status code
func (o *ListProjectGCPNetworksOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list project g c p networks o k response has a 3xx status code
func (o *ListProjectGCPNetworksOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list project g c p networks o k response has a 4xx status code
func (o *ListProjectGCPNetworksOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list project g c p networks o k response has a 5xx status code
func (o *ListProjectGCPNetworksOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list project g c p networks o k response a status code equal to that given
func (o *ListProjectGCPNetworksOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListProjectGCPNetworksOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/providers/gcp/networks][%d] listProjectGCPNetworksOK  %+v", 200, o.Payload)
}

func (o *ListProjectGCPNetworksOK) String() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/providers/gcp/networks][%d] listProjectGCPNetworksOK  %+v", 200, o.Payload)
}

func (o *ListProjectGCPNetworksOK) GetPayload() models.GCPNetworkList {
	return o.Payload
}

func (o *ListProjectGCPNetworksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListProjectGCPNetworksDefault creates a ListProjectGCPNetworksDefault with default headers values
func NewListProjectGCPNetworksDefault(code int) *ListProjectGCPNetworksDefault {
	return &ListProjectGCPNetworksDefault{
		_statusCode: code,
	}
}

/*
ListProjectGCPNetworksDefault describes a response with status code -1, with default header values.

errorResponse
*/
type ListProjectGCPNetworksDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the list project g c p networks default response
func (o *ListProjectGCPNetworksDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this list project g c p networks default response has a 2xx status code
func (o *ListProjectGCPNetworksDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list project g c p networks default response has a 3xx status code
func (o *ListProjectGCPNetworksDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list project g c p networks default response has a 4xx status code
func (o *ListProjectGCPNetworksDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list project g c p networks default response has a 5xx status code
func (o *ListProjectGCPNetworksDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list project g c p networks default response a status code equal to that given
func (o *ListProjectGCPNetworksDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ListProjectGCPNetworksDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/providers/gcp/networks][%d] listProjectGCPNetworks default  %+v", o._statusCode, o.Payload)
}

func (o *ListProjectGCPNetworksDefault) String() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/providers/gcp/networks][%d] listProjectGCPNetworks default  %+v", o._statusCode, o.Payload)
}

func (o *ListProjectGCPNetworksDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListProjectGCPNetworksDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
