// Code generated by go-swagger; DO NOT EDIT.

package applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteApplicationDefinitionParams creates a new DeleteApplicationDefinitionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteApplicationDefinitionParams() *DeleteApplicationDefinitionParams {
	return &DeleteApplicationDefinitionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteApplicationDefinitionParamsWithTimeout creates a new DeleteApplicationDefinitionParams object
// with the ability to set a timeout on a request.
func NewDeleteApplicationDefinitionParamsWithTimeout(timeout time.Duration) *DeleteApplicationDefinitionParams {
	return &DeleteApplicationDefinitionParams{
		timeout: timeout,
	}
}

// NewDeleteApplicationDefinitionParamsWithContext creates a new DeleteApplicationDefinitionParams object
// with the ability to set a context for a request.
func NewDeleteApplicationDefinitionParamsWithContext(ctx context.Context) *DeleteApplicationDefinitionParams {
	return &DeleteApplicationDefinitionParams{
		Context: ctx,
	}
}

// NewDeleteApplicationDefinitionParamsWithHTTPClient creates a new DeleteApplicationDefinitionParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteApplicationDefinitionParamsWithHTTPClient(client *http.Client) *DeleteApplicationDefinitionParams {
	return &DeleteApplicationDefinitionParams{
		HTTPClient: client,
	}
}

/*
DeleteApplicationDefinitionParams contains all the parameters to send to the API endpoint

	for the delete application definition operation.

	Typically these are written to a http.Request.
*/
type DeleteApplicationDefinitionParams struct {

	// AppdefName.
	AppDefName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete application definition params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteApplicationDefinitionParams) WithDefaults() *DeleteApplicationDefinitionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete application definition params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteApplicationDefinitionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete application definition params
func (o *DeleteApplicationDefinitionParams) WithTimeout(timeout time.Duration) *DeleteApplicationDefinitionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete application definition params
func (o *DeleteApplicationDefinitionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete application definition params
func (o *DeleteApplicationDefinitionParams) WithContext(ctx context.Context) *DeleteApplicationDefinitionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete application definition params
func (o *DeleteApplicationDefinitionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete application definition params
func (o *DeleteApplicationDefinitionParams) WithHTTPClient(client *http.Client) *DeleteApplicationDefinitionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete application definition params
func (o *DeleteApplicationDefinitionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppDefName adds the appdefName to the delete application definition params
func (o *DeleteApplicationDefinitionParams) WithAppDefName(appdefName string) *DeleteApplicationDefinitionParams {
	o.SetAppDefName(appdefName)
	return o
}

// SetAppDefName adds the appdefName to the delete application definition params
func (o *DeleteApplicationDefinitionParams) SetAppDefName(appdefName string) {
	o.AppDefName = appdefName
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteApplicationDefinitionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param appdef_name
	if err := r.SetPathParam("appdef_name", o.AppDefName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
