// Code generated by go-swagger; DO NOT EDIT.

package resource_quota

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"k8c.io/dashboard/v2/pkg/test/e2e/utils/apiclient/models"
)

// GetTotalResourceQuotaReader is a Reader for the GetTotalResourceQuota structure.
type GetTotalResourceQuotaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTotalResourceQuotaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTotalResourceQuotaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetTotalResourceQuotaUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetTotalResourceQuotaForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetTotalResourceQuotaDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetTotalResourceQuotaOK creates a GetTotalResourceQuotaOK with default headers values
func NewGetTotalResourceQuotaOK() *GetTotalResourceQuotaOK {
	return &GetTotalResourceQuotaOK{}
}

/*
GetTotalResourceQuotaOK describes a response with status code 200, with default header values.

ResourceQuota
*/
type GetTotalResourceQuotaOK struct {
	Payload *models.ResourceQuota
}

// IsSuccess returns true when this get total resource quota o k response has a 2xx status code
func (o *GetTotalResourceQuotaOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get total resource quota o k response has a 3xx status code
func (o *GetTotalResourceQuotaOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get total resource quota o k response has a 4xx status code
func (o *GetTotalResourceQuotaOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get total resource quota o k response has a 5xx status code
func (o *GetTotalResourceQuotaOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get total resource quota o k response a status code equal to that given
func (o *GetTotalResourceQuotaOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetTotalResourceQuotaOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/totalquota][%d] getTotalResourceQuotaOK  %+v", 200, o.Payload)
}

func (o *GetTotalResourceQuotaOK) String() string {
	return fmt.Sprintf("[GET /api/v2/totalquota][%d] getTotalResourceQuotaOK  %+v", 200, o.Payload)
}

func (o *GetTotalResourceQuotaOK) GetPayload() *models.ResourceQuota {
	return o.Payload
}

func (o *GetTotalResourceQuotaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResourceQuota)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTotalResourceQuotaUnauthorized creates a GetTotalResourceQuotaUnauthorized with default headers values
func NewGetTotalResourceQuotaUnauthorized() *GetTotalResourceQuotaUnauthorized {
	return &GetTotalResourceQuotaUnauthorized{}
}

/*
GetTotalResourceQuotaUnauthorized describes a response with status code 401, with default header values.

EmptyResponse is a empty response
*/
type GetTotalResourceQuotaUnauthorized struct {
}

// IsSuccess returns true when this get total resource quota unauthorized response has a 2xx status code
func (o *GetTotalResourceQuotaUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get total resource quota unauthorized response has a 3xx status code
func (o *GetTotalResourceQuotaUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get total resource quota unauthorized response has a 4xx status code
func (o *GetTotalResourceQuotaUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get total resource quota unauthorized response has a 5xx status code
func (o *GetTotalResourceQuotaUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get total resource quota unauthorized response a status code equal to that given
func (o *GetTotalResourceQuotaUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *GetTotalResourceQuotaUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v2/totalquota][%d] getTotalResourceQuotaUnauthorized ", 401)
}

func (o *GetTotalResourceQuotaUnauthorized) String() string {
	return fmt.Sprintf("[GET /api/v2/totalquota][%d] getTotalResourceQuotaUnauthorized ", 401)
}

func (o *GetTotalResourceQuotaUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTotalResourceQuotaForbidden creates a GetTotalResourceQuotaForbidden with default headers values
func NewGetTotalResourceQuotaForbidden() *GetTotalResourceQuotaForbidden {
	return &GetTotalResourceQuotaForbidden{}
}

/*
GetTotalResourceQuotaForbidden describes a response with status code 403, with default header values.

EmptyResponse is a empty response
*/
type GetTotalResourceQuotaForbidden struct {
}

// IsSuccess returns true when this get total resource quota forbidden response has a 2xx status code
func (o *GetTotalResourceQuotaForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get total resource quota forbidden response has a 3xx status code
func (o *GetTotalResourceQuotaForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get total resource quota forbidden response has a 4xx status code
func (o *GetTotalResourceQuotaForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get total resource quota forbidden response has a 5xx status code
func (o *GetTotalResourceQuotaForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get total resource quota forbidden response a status code equal to that given
func (o *GetTotalResourceQuotaForbidden) IsCode(code int) bool {
	return code == 403
}

func (o *GetTotalResourceQuotaForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/totalquota][%d] getTotalResourceQuotaForbidden ", 403)
}

func (o *GetTotalResourceQuotaForbidden) String() string {
	return fmt.Sprintf("[GET /api/v2/totalquota][%d] getTotalResourceQuotaForbidden ", 403)
}

func (o *GetTotalResourceQuotaForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTotalResourceQuotaDefault creates a GetTotalResourceQuotaDefault with default headers values
func NewGetTotalResourceQuotaDefault(code int) *GetTotalResourceQuotaDefault {
	return &GetTotalResourceQuotaDefault{
		_statusCode: code,
	}
}

/*
GetTotalResourceQuotaDefault describes a response with status code -1, with default header values.

errorResponse
*/
type GetTotalResourceQuotaDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the get total resource quota default response
func (o *GetTotalResourceQuotaDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this get total resource quota default response has a 2xx status code
func (o *GetTotalResourceQuotaDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get total resource quota default response has a 3xx status code
func (o *GetTotalResourceQuotaDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get total resource quota default response has a 4xx status code
func (o *GetTotalResourceQuotaDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get total resource quota default response has a 5xx status code
func (o *GetTotalResourceQuotaDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get total resource quota default response a status code equal to that given
func (o *GetTotalResourceQuotaDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *GetTotalResourceQuotaDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/totalquota][%d] getTotalResourceQuota default  %+v", o._statusCode, o.Payload)
}

func (o *GetTotalResourceQuotaDefault) String() string {
	return fmt.Sprintf("[GET /api/v2/totalquota][%d] getTotalResourceQuota default  %+v", o._statusCode, o.Payload)
}

func (o *GetTotalResourceQuotaDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetTotalResourceQuotaDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
