# Copyright 2022 The Kubermatic Kubernetes Platform contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

run:
  modules-download-mode: readonly
  timeout: 20m
  build-tags:
    - ce
    - cloud
    - create
    - dualstack
    - e2e
    - ee
    - integration
    - ipam
    - kubevirt
    - logout

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - depguard
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - promlinter
    - staticcheck
    - tenv
    - unconvert
    - unused
    - wastedassign
    - whitespace
  disable-all: true

# NOTE: Do not use commas in the exclude patterns, or else the regex will be
# split and you will be sad: https://github.com/golangci/golangci-lint/issues/665
issues:
  exclude:
    # gocyclo
    - cyclomatic complexity [0-9]+ of func `initTestEndpoint` is high
    - cyclomatic complexity [0-9]+ of func `GetAPIV2NodeCloudSpec` is high
    - loop variable tc captured by func literal
    # TODO (sig-api): fix the following issues
    - cfg.EndpointResolverWithOptions is deprecated
  exclude-files:
    # This package was forked from upstream (in #9826)
    # and we want to keep it as close to upstream as possible.
    - modules/api/pkg/provider/cloud/eks/authenticator

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - { pkg: io/ioutil, desc: https://go.dev/doc/go1.16#ioutil }

  importas:
    no-unaliased: true
    alias:
      # KKP
      - pkg: k8c.io/kubermatic/v2/sdk/api/v1
        alias: apiv1
      - pkg: k8c.io/kubermatic/v2/sdk/api/v2
        alias: apiv2
      - pkg: k8c.io/kubermatic/v2/sdk/apis/apps.kubermatic/v1
        alias: appskubermaticv1
      - pkg: k8c.io/kubermatic/v2/sdk/apis/kubermatic/v1
        alias: kubermaticv1
      - pkg: k8c.io/kubermatic/v2/pkg/util/errors
        alias: utilerrors
      - pkg: k8c.io/dashboard/v2/pkg/provider/auth/types
        alias: authtypes
      # Kubernetes
      - pkg: k8s.io/api/(\w+)/(v[\w\d]+)
        alias: $1$2
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
        alias: apiextensionsv1
      - pkg: k8s.io/apimachinery/pkg/api/errors
        alias: apierrors
      - pkg: k8s.io/apimachinery/pkg/util/errors
        alias: kerrors
      # Controller Runtime
      - pkg: sigs.k8s.io/controller-runtime/pkg/client
        alias: ctrlruntimeclient
      # Misc
      - pkg: k8c.io/machine-controller/pkg/apis/cluster/v1alpha1
        alias: clusterv1alpha1
      - pkg: github.com/Masterminds/semver/v3
        alias: semverlib
